version: '3'
services:
  zookeeper:
    container_name: zookeeper
    image: 'zookeeper:3.4.14'
    network_mode: host
    ports:
      - '2181:2181'
    #networks:
    #  - kafka-network

  kafka:
    container_name: kafka
    image: 'confluentinc/cp-kafka:5.5.1'
    network_mode: host
    ports:
      - '9092:9092'
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=localhost:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
    depends_on:
      - zookeeper
    #networks:
    #  - kafka-network
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

#networks:
#  kafka-network:
#    driver: bridge

# We need to disable host network and enable bridge network later
